# Generated by Django 3.2.4 on 2024-01-23 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='room',
            name='uid',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
